version: '3'

services:
  frontend:
    container_name: Frontend
    build: 
      context: ./FrontendImageUploading
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: Backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=imageeditor
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    container_name: Database
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=imageeditor
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
