version: '3'

services:
  frontend:
    container_name: Frontend
    build: 
      context: ./FrontendImageUploading
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.todo-app.rule=Host(`${HOST_ADDRESS}`) && !PathPrefix(`/api`)" # evrthing but api
      - "traefik.http.routers.todo-app.tls=true"
      - "traefik.http.routers.todo-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.todo-app.entrypoints=websecure"
    volumes:
      - ./server/uploads:/usr/share/nginx/html/uploads
    networks:
      - traefik-public
      - backend-network

  backend:
    container_name: Backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.todo-api.rule=Host(`${HOST_ADDRESS}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.todo-api.tls=true"
      - "traefik.http.routers.todo-api.tls.certresolver=letsencrypt"
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - traefik-public
      - backend-network
    depends_on:
      - db

  db:
    container_name: Database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

networks:
  traefik-public:
    external: true
  backend-network:
    driver: bridge

volumes:
  mysql_data:
