version: '3'

services:
  frontend:
    container_name: Frontend
    build: 
      context: ./FrontendImageUploading
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`imageeditor.localhost`) && !PathPrefix(`/api`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    volumes:
      - ./server/uploads:/usr/share/nginx/html/uploads
    networks:
      - traefik-public
      - backend-network
    depends_on:
      - backend

  backend:
    container_name: Backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`imageeditor.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.cors-backend.headers.accessControlAllowMethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors-backend.headers.accessControlAllowOriginList=*"
      - "traefik.http.middlewares.cors-backend.headers.accessControlAllowHeaders=*"
      - "traefik.http.middlewares.cors-backend.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.cors-backend.headers.addVaryHeader=true"
      - "traefik.http.routers.backend.middlewares=cors-backend"
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - traefik-public
      - backend-network
    depends_on:
      - db

  db:
    container_name: Database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network

networks:
  traefik-public:
    external: true
  backend-network:
    driver: bridge

volumes:
  mysql_data:
