version: '3'

services:
  frontend:
    container_name: Frontend
    build: 
      context: ./FrontendImageUploading
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./server/uploads:/usr/share/nginx/html/uploads

  backend:
    container_name: Backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - db

  db:
    container_name: Database
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=imageeditor
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
