http:
  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend"

    backend:
      loadBalancer:
        servers:
          - url: "http://backend:3000"

    jenkins:
      loadBalancer:
        servers:
          - url: "http://jenkins:8080"

  routers:
    jenkins:
      rule: "PathPrefix(`/jenkins`)"
      service: jenkins
      middlewares:
        - "jenkins-strip"

  middlewares:
    jenkins-strip:
      stripPrefix:
        prefixes: 
          - "/jenkins"
