version: "3"
services:
  jenkins:
    image: jenkins/jenkins:jdk11
    ports:
      - "8082:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssh:/home/jenkins/.ssh
    networks:
      - traefik-public
volumes:
  jenkins-data:
networks:
  traefik-public:
    external: true
