version: "3"
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    env_file:
      - ./ssh/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=PathPrefix(`/jenkins`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    ports:
      - "8082:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ssh:/home/jenkins/.ssh 
    networks:
      - traefik-public
volumes:
  jenkins-data:
networks:
  traefik-public:
    external: true
